### ISSUE TITLE
Flashing the BeeHive - missing firmware and bootloader from the manual

### ISSUE THREAD

**Issue by nonszalancki** [jakplugg/beehive#6]
Hi there,

The Antumbra Knit website mentioned in Flashing the Beehive.pdf doesn't have the firmware and bootloader for download. Any alternatives besides compiling from Mutable Instruments Plaits repo?

**Comment by jasonnolan** [comment]
That stuff was available, so I just made up the Flashing the Beehive instructions because it didn't exist. You can google alternative firmware for plaits and there will be stuff. Good luck.

**Comment by nonszalancki** [comment]
Case closed. Thank you @jasonnolan for clarifiyng ;)
